{% set version = "0.3.1" %}

package:
  name: metpy
  version: {{ version }}

source:
  fn: metpy-{{version}}.tar.gz
  url: https://pypi.io/packages/source/M/MetPy/MetPy-{{version}}.tar.gz
  md5: 9284a5f33f28f7dc7c599d92f0d20373

build:
    script: python setup.py install --single-version-externally-managed --record record.txt
    number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.8.0
    - scipy >=0.13.3
    - matplotlib >=1.4.0
    - pint >=0.6
    - enum34  # [py27]

test:
  imports:
    - metpy.calc
    - metpy.plots
    - metpy.io

about:
  home: https://github.com/metpy/MetPy
  license: BSD 3-Clause
  summary: 'MetPy is a collection of tools in Python for reading, visualizing and performing calculations with weather data.'

extra:
  recipe-maintainers:
    - dopplershift
