{% set version = "0.4.0" %}

package:
  name: metpy
  version: {{ version }}

source:
  fn: metpy-{{version}}.tar.gz
  url: https://pypi.io/packages/source/M/MetPy/MetPy-{{version}}.tar.gz
  sha256: f752ddd533e24e3de86f29c61c8d56035b6638e5a3d0c3c762378e147742ab20

build:
    script: python setup.py install --single-version-externally-managed --record record.txt
    number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.9.1
    - scipy >=0.13.3
    - matplotlib >=1.4.0
    - pint >=0.7
    - enum34  # [py27]

test:
  imports:
    - metpy.calc
    - metpy.plots
    - metpy.io

about:
  home: https://github.com/metpy/MetPy
  license: BSD 3-Clause
  summary: 'MetPy is a collection of tools in Python for reading, visualizing and performing calculations with weather data.'

extra:
  recipe-maintainers:
    - dopplershift
