travis:
  secure:
    BINSTAR_TOKEN: rDUpvYTvbISor1jg0Ajj+LNAebriT2yDimx6GxisGCCGLXvgVcqut4dkx3J1XpYa/WeuMIe2usmNFOrK2xNxt2yF6Xgzp1sYmOlISFZ5Yji17+T2jRfZsFtIr+nXqJWZQxubnlQ/DjaoYa7Efeimg7bjmvL6563NSrwi2gEhVh1YeAywy7jTs+l5+8YPIGs0pruCVzPgYXRxfoU4KxUeHvd2w/q/0hZzcRQ9LUvlbO0eGUNRGke4QEwHWxXDd2MBzL5ZmZIxoNE4SWYYQmJQ/brQ5Et6xomNXYSdKnYxmmyuTsrVlj081UTqv2xj82KC+PCXhsOTzYT4pYle1wbV2C6kZSoetmF742863agmXH2AtaEDkK/CbgSA1B3g4bg2/R5QdY5n09ewKUbGtTOeYBcmQdh0E7Hpm6Aryj098twVUixeRlXMQN3daflJI01k+UQFByBUBSCPuaY7HyUxBEpduVo48+XvsMbKONhPMbRkS1NigoCkygk3er5/w8IBYZ2gRQYGU44/uhBVhPFHrKIoMlNTHQoSPvfRmdctOIuWLXssiyztulsABabdPKIH1VWcmDRDblDlaB1Tc7cGo9EcJWl0IRwT3XHMKvBRZ41hPxqW/1MTSWS/hjcnMXWwgBUGrZBraLXu0192z+WKujm8iY8S49mud0QDhRHt/tY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
